const DEFAULT_ERROR_MESSAGE = "Something went wrong";
const DEFAULT_PAGE_SIZE = 12;
const DEFAULT_INITIAL_PAGE = 1;
const HTTP_NOT_FOUND = 404;
const HTTP_INTERNAL_SERVER_ERROR = 500;

export {
	DEFAULT_ERROR_MESSAGE,
	DEFAULT_PAGE_SIZE,
	DEFAULT_INITIAL_PAGE,
	HTTP_NOT_FOUND,
	HTTP_INTERNAL_SERVER_ERROR,
};
